[package]
name = "serial"
version = "0.0.1"
authors = ["Carsten Andrich <carsten@andrich.name>"]
edition = "2018"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
udev = "0.4"

[target.'cfg(windows)'.dependencies]
if_rust_version = "1.0.0"
winapi = { version = "0.3", features = ["std", "commapi", "errhandlingapi", "fileapi", "handleapi", "ioapiset", "synchapi", "winbase", "winerror", "winnt"] }

[features]
experimental = []
